apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: eureka-server
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: dyuthik/eureka-server
        ports:
        - containerPort: 8761